apiVersion: bigquery.cnrm.cloud.google.com/v1beta1
kind: BigQueryDataset
metadata:
  name: "{{dataset}}"
  namespace: teamdagpenger
  labels:
    team: teamdagpenger
  annotations:
    cnrm.cloud.google.com/management-conflict-prevention-policy: none
    cnrm.cloud.google.com/state-into-spec: absent
spec:
  resourceID: events
  location: europe-north1
  description: Datasett for dp-event
  projectRef:
    external: "{{project}}"
